### GET request to example server
GET http://localhost:8000/member/count
Accept: application/json


###
POST http://localhost:8000/member/register
Content-Type: application/x-www-form-urlencoded

mobile=22508



###